2022-10-30 19:59:54,590 [main] INFO org.apache.hadoop.ozone.HddsDatanodeService: STARTUP_MSG: 
/************************************************************
STARTUP_MSG: Starting HddsDatanodeService
STARTUP_MSG:   host = rhel9dev/192.168.15.20
STARTUP_MSG:   args = []
STARTUP_MSG:   version = 1.2.1
STARTUP_MSG:   classpath = /ozone/etc/hadoop:/ozone/share/ozone/lib/kerb-simplekdc-1.0.1.jar:/ozone/share/ozone/lib/jackson-annotations-2.12.1.jar:/ozone/share/ozone/lib/slf4j-log4j12-1.7.30.jar:/ozone/share/ozone/lib/protobuf-java-2.5.0.jar:/ozone/share/ozone/lib/jaxb-core-2.3.0.1.jar:/ozone/share/ozone/lib/istack-commons-runtime-3.0.5.jar:/ozone/share/ozone/lib/commons-validator-1.6.jar:/ozone/share/ozone/lib/bcpkix-jdk15on-1.67.jar:/ozone/share/ozone/lib/jetty-security-9.4.43.v20210629.jar:/ozone/share/ozone/lib/kerb-core-1.0.1.jar:/ozone/share/ozone/lib/rocksdbjni-6.20.3.jar:/ozone/share/ozone/lib/hadoop-shaded-protobuf_3_7-1.1.1.jar:/ozone/share/ozone/lib/okhttp-4.9.0.jar:/ozone/share/ozone/lib/jsr305-3.0.0.jar:/ozone/share/ozone/lib/j2objc-annotations-1.3.jar:/ozone/share/ozone/lib/htrace-core4-4.1.0-incubating.jar:/ozone/share/ozone/lib/picocli-4.6.1.jar:/ozone/share/ozone/lib/javassist-3.21.0-GA.jar:/ozone/share/ozone/lib/jaxb-api-2.3.0.jar:/ozone/share/ozone/lib/commons-io-2.8.0.jar:/ozone/share/ozone/lib/kerb-util-1.0.1.jar:/ozone/share/ozone/lib/kotlin-stdlib-common-1.4.31.jar:/ozone/share/ozone/lib/hadoop-shaded-guava-1.1.1.jar:/ozone/share/ozone/lib/checker-qual-3.8.0.jar:/ozone/share/ozone/lib/commons-logging-1.2.jar:/ozone/share/ozone/lib/kerby-xdr-1.0.1.jar:/ozone/share/ozone/lib/netty-buffer-4.1.63.Final.jar:/ozone/share/ozone/lib/hdds-interface-admin-1.2.1.jar:/ozone/share/ozone/lib/log4j-core-2.16.0.jar:/ozone/share/ozone/lib/txw2-2.3.0.1.jar:/ozone/share/ozone/lib/jackson-datatype-jsr310-2.12.1.jar:/ozone/share/ozone/lib/httpcore-4.4.13.jar:/ozone/share/ozone/lib/opentracing-tracerresolver-0.1.8.jar:/ozone/share/ozone/lib/commons-net-3.6.jar:/ozone/share/ozone/lib/libthrift-0.14.1.jar:/ozone/share/ozone/lib/snakeyaml-1.26.jar:/ozone/share/ozone/lib/stax-ex-1.7.8.jar:/ozone/share/ozone/lib/httpclient-4.5.13.jar:/ozone/share/ozone/lib/jetty-servlet-9.4.43.v20210629.jar:/ozone/share/ozone/lib/kerby-config-1.0.1.jar:/ozone/share/ozone/lib/jaeger-client-1.6.0.jar:/ozone/share/ozone/lib/metrics-core-3.2.4.jar:/ozone/share/ozone/lib/kerby-pkix-1.0.1.jar:/ozone/share/ozone/lib/activation-1.1.1.jar:/ozone/share/ozone/lib/jsr311-api-1.1.1.jar:/ozone/share/ozone/lib/netty-codec-4.1.63.Final.jar:/ozone/share/ozone/lib/jetty-webapp-9.4.43.v20210629.jar:/ozone/share/ozone/lib/commons-beanutils-1.9.4.jar:/ozone/share/ozone/lib/javax.servlet-api-3.1.0.jar:/ozone/share/ozone/lib/kerb-server-1.0.1.jar:/ozone/share/ozone/lib/guava-30.1.1-jre.jar:/ozone/share/ozone/lib/kerb-client-1.0.1.jar:/ozone/share/ozone/lib/jackson-core-2.12.1.jar:/ozone/share/ozone/lib/netty-transport-4.1.63.Final.jar:/ozone/share/ozone/lib/ratis-grpc-2.2.0.jar:/ozone/share/ozone/lib/ratis-common-2.2.0.jar:/ozone/share/ozone/lib/netty-common-4.1.63.Final.jar:/ozone/share/ozone/lib/disruptor-3.4.2.jar:/ozone/share/ozone/lib/reflections-0.9.11.jar:/ozone/share/ozone/lib/hdds-hadoop-dependency-server-1.2.1.jar:/ozone/share/ozone/lib/jetty-io-9.4.43.v20210629.jar:/ozone/share/ozone/lib/hadoop-hdfs-3.3.1.jar:/ozone/share/ozone/lib/annotations-13.0.jar:/ozone/share/ozone/lib/jetty-server-9.4.43.v20210629.jar:/ozone/share/ozone/lib/jackson-databind-2.12.1.jar:/ozone/share/ozone/lib/simpleclient_common-0.7.0.jar:/ozone/share/ozone/lib/hadoop-common-3.3.1.jar:/ozone/share/ozone/lib/dnsjava-2.1.7.jar:/ozone/share/ozone/lib/jaeger-thrift-1.6.0.jar:/ozone/share/ozone/lib/bcprov-jdk15on-1.67.jar:/ozone/share/ozone/lib/commons-configuration2-2.1.1.jar:/ozone/share/ozone/lib/json-smart-2.3.jar:/ozone/share/ozone/lib/token-provider-1.0.1.jar:/ozone/share/ozone/lib/ratis-proto-2.2.0.jar:/ozone/share/ozone/lib/ratis-client-2.2.0.jar:/ozone/share/ozone/lib/log4j-1.2.17.jar:/ozone/share/ozone/lib/commons-daemon-1.0.13.jar:/ozone/share/ozone/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/ozone/share/ozone/lib/jetty-xml-9.4.43.v20210629.jar:/ozone/share/ozone/lib/jaeger-tracerresolver-1.6.0.jar:/ozone/share/ozone/lib/ratis-netty-2.2.0.jar:/ozone/share/ozone/lib/hdds-client-1.2.1.jar:/ozone/share/ozone/lib/commons-lang3-3.7.jar:/ozone/share/ozone/lib/hdds-interface-client-1.2.1.jar:/ozone/share/ozone/lib/accessors-smart-1.2.jar:/ozone/share/ozone/lib/re2j-1.1.jar:/ozone/share/ozone/lib/hdds-hadoop-dependency-client-1.2.1.jar:/ozone/share/ozone/lib/hdds-config-1.2.1.jar:/ozone/share/ozone/lib/commons-math3-3.1.1.jar:/ozone/share/ozone/lib/ratis-thirdparty-misc-0.7.0.jar:/ozone/share/ozone/lib/simpleclient_dropwizard-0.7.0.jar:/ozone/share/ozone/lib/simpleclient-0.7.0.jar:/ozone/share/ozone/lib/asm-5.0.4.jar:/ozone/share/ozone/lib/kerby-util-1.0.1.jar:/ozone/share/ozone/lib/failureaccess-1.0.1.jar:/ozone/share/ozone/lib/okio-2.8.0.jar:/ozone/share/ozone/lib/jsp-api-2.1.jar:/ozone/share/ozone/lib/jetty-http-9.4.43.v20210629.jar:/ozone/share/ozone/lib/jsch-0.1.54.jar:/ozone/share/ozone/lib/jakarta.activation-api-1.2.1.jar:/ozone/share/ozone/lib/slf4j-api-1.7.30.jar:/ozone/share/ozone/lib/hadoop-hdfs-client-3.3.1.jar:/ozone/share/ozone/lib/nimbus-jose-jwt-7.9.jar:/ozone/share/ozone/lib/commons-codec-1.11.jar:/ozone/share/ozone/lib/commons-pool2-2.6.0.jar:/ozone/share/ozone/lib/jetty-util-9.4.43.v20210629.jar:/ozone/share/ozone/lib/gson-2.2.4.jar:/ozone/share/ozone/lib/netty-handler-4.1.63.Final.jar:/ozone/share/ozone/lib/jetty-util-ajax-9.4.43.v20210629.jar:/ozone/share/ozone/lib/opentracing-api-0.33.0.jar:/ozone/share/ozone/lib/jcip-annotations-1.0-1.jar:/ozone/share/ozone/lib/kerb-admin-1.0.1.jar:/ozone/share/ozone/lib/netty-resolver-4.1.63.Final.jar:/ozone/share/ozone/lib/kotlin-stdlib-1.4.31.jar:/ozone/share/ozone/lib/opentracing-noop-0.33.0.jar:/ozone/share/ozone/lib/jersey-core-1.19.jar:/ozone/share/ozone/lib/jaxb-runtime-2.3.0.1.jar:/ozone/share/ozone/lib/log4j-api-2.16.0.jar:/ozone/share/ozone/lib/hdds-container-service-1.2.1.jar:/ozone/share/ozone/lib/ratis-metrics-2.2.0.jar:/ozone/share/ozone/lib/ratis-server-api-2.2.0.jar:/ozone/share/ozone/lib/opentracing-util-0.33.0.jar:/ozone/share/ozone/lib/snappy-java-1.1.8.2.jar:/ozone/share/ozone/lib/commons-cli-1.2.jar:/ozone/share/ozone/lib/woodstox-core-5.0.3.jar:/ozone/share/ozone/lib/javax.annotation-api-1.2.jar:/ozone/share/ozone/lib/kerby-asn1-1.0.1.jar:/ozone/share/ozone/lib/hadoop-annotations-3.3.1.jar:/ozone/share/ozone/lib/hdds-interface-server-1.2.1.jar:/ozone/share/ozone/lib/stax2-api-3.1.4.jar:/ozone/share/ozone/lib/commons-collections-3.2.2.jar:/ozone/share/ozone/lib/commons-digester-1.8.1.jar:/ozone/share/ozone/lib/jaeger-core-1.6.0.jar:/ozone/share/ozone/lib/hdds-server-framework-1.2.1.jar:/ozone/share/ozone/lib/commons-text-1.4.jar:/ozone/share/ozone/lib/jersey-servlet-1.19.jar:/ozone/share/ozone/lib/hadoop-auth-3.3.1.jar:/ozone/share/ozone/lib/kerb-identity-1.0.1.jar:/ozone/share/ozone/lib/ratis-server-2.2.0.jar:/ozone/share/ozone/lib/FastInfoset-1.2.13.jar:/ozone/share/ozone/lib/kerb-common-1.0.1.jar:/ozone/share/ozone/lib/jersey-server-1.19.jar:/ozone/share/ozone/lib/commons-compress-1.20.jar:/ozone/share/ozone/lib/hdds-common-1.2.1.jar:/ozone/share/ozone/lib/kerb-crypto-1.0.1.jar:/ozone/share/ozone/web:/ozone/share/ozone/lib/ozone-datanode-1.2.1.jar
STARTUP_MSG:   build = https://github.com/apache/ozone.git/76aa27e7c05196ae00cba540efce4bb7529e5d15 ; compiled by 'ethanrose' on 2021-12-15T22:27Z
STARTUP_MSG:   java = 11.0.16
************************************************************/
2022-10-30 19:59:54,594 [main] INFO org.apache.hadoop.ozone.HddsDatanodeService: registered UNIX signal handlers for [TERM, HUP, INT]
2022-10-30 19:59:54,717 [main] INFO org.apache.ratis.metrics.MetricRegistries: Loaded MetricRegistries class org.apache.ratis.metrics.impl.MetricRegistriesImpl
2022-10-30 19:59:54,770 [main] INFO org.apache.hadoop.metrics2.impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
2022-10-30 19:59:54,843 [main] INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2022-10-30 19:59:54,843 [main] INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: HddsDatanode metrics system started
2022-10-30 19:59:54,902 [main] INFO org.apache.hadoop.ozone.HddsDatanodeService: HddsDatanodeService host:rhel9dev ip:192.168.15.20
2022-10-30 19:59:55,805 [main] INFO org.apache.hadoop.ozone.upgrade.AbstractLayoutVersionManager: Initializing Layout version manager with metadata layout = SCM_HA (version = 2), software layout = SCM_HA (version = 2)
2022-10-30 19:59:55,877 [main] INFO org.reflections.Reflections: Reflections took 53 ms to scan 2 urls, producing 84 keys and 167 values 
2022-10-30 19:59:55,991 [main] INFO org.apache.hadoop.hdds.fs.SaveSpaceUsageToFile: Cached usage info file /tmp/hadoop-rhel9dev/dfs/data/scmUsed not found
2022-10-30 19:59:55,994 [main] INFO org.apache.hadoop.ozone.container.common.volume.HddsVolume: Creating HddsVolume: /tmp/hadoop-rhel9dev/dfs/data/hdds of storage type : DISK capacity : 1499268128768
2022-10-30 19:59:55,995 [main] INFO org.apache.hadoop.ozone.container.common.volume.MutableVolumeSet: Added Volume : /tmp/hadoop-rhel9dev/dfs/data/hdds to VolumeSet
2022-10-30 19:59:55,996 [main] INFO org.apache.hadoop.ozone.container.common.volume.ThrottledAsyncChecker: Scheduling a check for /tmp/hadoop-rhel9dev/dfs/data/hdds
2022-10-30 19:59:56,010 [main] INFO org.apache.hadoop.ozone.container.common.volume.StorageVolumeChecker: Scheduled health check for volume /tmp/hadoop-rhel9dev/dfs/data/hdds
2022-10-30 19:59:56,020 [main] WARN org.apache.hadoop.hdds.server.ServerUtils: Storage directory for Ratis is not configured. It is a good idea to map this to an SSD disk. Falling back to ozone.metadata.dirs
2022-10-30 19:59:56,021 [main] INFO org.apache.hadoop.hdds.fs.SaveSpaceUsageToFile: Cached usage info file /ozone/data/meta/ratis/scmUsed not found
2022-10-30 19:59:56,021 [main] INFO org.apache.hadoop.ozone.container.common.volume.MutableVolumeSet: Added Volume : /ozone/data/meta/ratis to VolumeSet
2022-10-30 19:59:56,021 [main] INFO org.apache.hadoop.ozone.container.common.volume.ThrottledAsyncChecker: Scheduling a check for /ozone/data/meta/ratis
2022-10-30 19:59:56,021 [main] INFO org.apache.hadoop.ozone.container.common.volume.StorageVolumeChecker: Scheduled health check for volume /ozone/data/meta/ratis
2022-10-30 19:59:56,033 [Thread-5] INFO org.apache.hadoop.ozone.container.ozoneimpl.ContainerReader: Finish verifying containers on volume /tmp/hadoop-rhel9dev/dfs/data/hdds
2022-10-30 19:59:56,033 [main] INFO org.apache.hadoop.ozone.container.ozoneimpl.OzoneContainer: Build ContainerSet costs 0s
2022-10-30 19:59:56,557 [main] WARN org.apache.hadoop.hdds.server.ServerUtils: Storage directory for Ratis is not configured. It is a good idea to map this to an SSD disk. Falling back to ozone.metadata.dirs
2022-10-30 19:59:56,583 [main] INFO org.apache.ratis.server.RaftServer: raft.rpc.type = GRPC (default)
2022-10-30 19:59:56,632 [main] INFO org.apache.ratis.grpc.GrpcConfigKeys: raft.grpc.admin.port = 9857 (custom)
2022-10-30 19:59:56,632 [main] INFO org.apache.ratis.grpc.GrpcConfigKeys: raft.grpc.client.port = 9858 (custom)
2022-10-30 19:59:56,633 [main] INFO org.apache.ratis.grpc.GrpcConfigKeys: raft.grpc.server.port = 9856 (custom)
2022-10-30 19:59:56,633 [main] INFO org.apache.ratis.grpc.server.GrpcService: raft.grpc.message.size.max = 32MB (=33554432) (custom)
2022-10-30 19:59:56,634 [main] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.log.appender.buffer.byte-limit = 33554432 (custom)
2022-10-30 19:59:56,634 [main] INFO org.apache.ratis.grpc.server.GrpcService: raft.grpc.flow.control.window = 5MB (=5242880) (custom)
2022-10-30 19:59:56,634 [main] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.request.timeout = 60s (custom)
2022-10-30 19:59:56,778 [main] INFO org.apache.ratis.server.impl.DataStreamServerImpl: raft.datastream.type = DISABLED (default)
2022-10-30 19:59:56,779 [main] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.slowness.timeout = 300s (custom)
2022-10-30 19:59:56,779 [main] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.leaderelection.leader.step-down.wait-time = 10s (default)
2022-10-30 19:59:56,786 [main] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.storage.dir = [/ozone/data/meta/ratis] (custom)
2022-10-30 19:59:56,788 [main] INFO org.apache.ratis.server.RaftServer: 7a4d425e-0004-4270-a08b-7d52bd28d47e: found a subdirectory /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
2022-10-30 19:59:56,791 [main] INFO org.apache.ratis.server.RaftServer: 7a4d425e-0004-4270-a08b-7d52bd28d47e: addNew group-C5BA1605619E:[] returns group-C5BA1605619E:java.util.concurrent.CompletableFuture@270a620[Not completed]
2022-10-30 19:59:56,885 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServer$Division: 7a4d425e-0004-4270-a08b-7d52bd28d47e: new RaftServerImpl for group-C5BA1605619E:[] with ContainerStateMachine:uninitialized
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.timeout.min = 5s (custom)
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.timeout.max = 5200ms (custom)
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.sleep.time = 25ms (default)
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.rpc.slowness.timeout = 300s (custom)
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.leaderelection.leader.step-down.wait-time = 10s (default)
2022-10-30 19:59:56,886 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.sleep.deviation.threshold = 300ms (default)
2022-10-30 19:59:56,887 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.log.appender.install.snapshot.enabled = false (custom)
2022-10-30 19:59:56,890 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServer$Division: 7a4d425e-0004-4270-a08b-7d52bd28d47e@group-C5BA1605619E: ConfigurationManager, init=-1: [], old=null, confs=<EMPTY_MAP>
2022-10-30 19:59:56,890 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.storage.dir = [/ozone/data/meta/ratis] (custom)
2022-10-30 19:59:56,891 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.log.corruption.policy = EXCEPTION (default)
2022-10-30 19:59:56,892 [pool-22-thread-1] INFO org.apache.ratis.server.RaftServerConfigKeys: raft.server.storage.free-space.min = 0MB (=0) (default)
2022-10-30 19:59:56,897 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: Unable to acquire file lock on path /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock
2022-10-30 19:59:56,898 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: It appears that another process has already locked the storage directory: /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-30 19:59:56,899 [pool-22-thread-1] WARN org.apache.ratis.util.FileUtils: FAILED "tryLock /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock", attempt #1/5: java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked, sleep 1s and then retry.
java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:236)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	... 15 more
2022-10-30 19:59:56,908 [main] INFO org.apache.hadoop.hdds.server.http.BaseHttpServer: Starting Web-server for hddsDatanode at: http://0.0.0.0:9882
2022-10-30 19:59:56,918 [main] INFO org.apache.hadoop.hdds.server.http.BaseHttpServer: Hadoop Security Enabled: false Ozone Security Enabled: false Ozone HTTP Security Enabled: false 
2022-10-30 19:59:56,934 [main] INFO org.eclipse.jetty.util.log: Logging initialized @2847ms to org.eclipse.jetty.util.log.Slf4jLog
2022-10-30 19:59:56,992 [main] INFO org.apache.hadoop.security.authentication.server.AuthenticationFilter: Unable to initialize FileSignerSecretProvider, falling back to use random secrets.
2022-10-30 19:59:56,994 [main] INFO org.apache.hadoop.hdds.server.http.HttpRequestLog: Http request log for http.requests.hddsDatanode is not defined
2022-10-30 19:59:56,997 [main] INFO org.apache.hadoop.hdds.server.http.HttpServer2: Added global filter 'safety' (class=org.apache.hadoop.hdds.server.http.HttpServer2$QuotingInputFilter)
2022-10-30 19:59:56,998 [main] INFO org.apache.hadoop.hdds.server.http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context hddsDatanode
2022-10-30 19:59:56,998 [main] INFO org.apache.hadoop.hdds.server.http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context logs
2022-10-30 19:59:56,998 [main] INFO org.apache.hadoop.hdds.server.http.HttpServer2: Added filter static_user_filter (class=org.apache.hadoop.http.lib.StaticUserWebFilter$StaticUserFilter) to context static
2022-10-30 19:59:57,026 [main] INFO org.apache.hadoop.hdds.server.http.HttpServer2: Jetty bound to port 9882
2022-10-30 19:59:57,026 [main] INFO org.eclipse.jetty.server.Server: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 11.0.16+8-LTS
2022-10-30 19:59:57,043 [main] INFO org.eclipse.jetty.server.session: DefaultSessionIdManager workerName=node0
2022-10-30 19:59:57,043 [main] INFO org.eclipse.jetty.server.session: No SessionScavenger set, using defaults
2022-10-30 19:59:57,044 [main] INFO org.eclipse.jetty.server.session: node0 Scavenging every 660000ms
2022-10-30 19:59:57,052 [main] INFO org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@724bf25f{logs,/logs,file:///ozone/logs/,AVAILABLE}
2022-10-30 19:59:57,052 [main] INFO org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@613f7eb7{static,/static,jar:file:/ozone/share/ozone/lib/hdds-container-service-1.2.1.jar!/webapps/static,AVAILABLE}
2022-10-30 19:59:57,214 [main] INFO org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.w.WebAppContext@5b02a984{hddsDatanode,/,file:///tmp/jetty-0_0_0_0-9882-hdds-container-service-1_2_1_jar-_-any-776367877629291575/webapp/,AVAILABLE}{jar:file:/ozone/share/ozone/lib/hdds-container-service-1.2.1.jar!/webapps/hddsDatanode}
2022-10-30 19:59:57,221 [main] INFO org.eclipse.jetty.server.AbstractConnector: Started ServerConnector@632b305d{HTTP/1.1, (http/1.1)}{0.0.0.0:9882}
2022-10-30 19:59:57,221 [main] INFO org.eclipse.jetty.server.Server: Started @3134ms
2022-10-30 19:59:57,222 [main] INFO org.apache.hadoop.metrics2.impl.MetricsSinkAdapter: Sink prometheus started
2022-10-30 19:59:57,222 [main] INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Registered sink prometheus
2022-10-30 19:59:57,223 [main] INFO org.apache.hadoop.hdds.server.http.BaseHttpServer: HTTP server of hddsDatanode listening at http://0.0.0.0:9882
2022-10-30 19:59:57,223 [Datanode State Machine Thread - 0] INFO org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine: Ozone container server started.
2022-10-30 19:59:57,230 [org.apache.hadoop.util.JvmPauseMonitor$Monitor@57962e3f] INFO org.apache.hadoop.util.JvmPauseMonitor: Starting JVM pause monitor
2022-10-30 19:59:57,288 [Datanode State Machine Task Thread - 0] INFO org.apache.hadoop.ozone.container.common.states.datanode.InitDatanodeState: DatanodeDetails is persisted to /ozone/data/meta/datanode.id
2022-10-30 19:59:57,900 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: Unable to acquire file lock on path /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock
2022-10-30 19:59:57,900 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: It appears that another process has already locked the storage directory: /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-30 19:59:57,901 [pool-22-thread-1] WARN org.apache.ratis.util.FileUtils: FAILED "tryLock /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock", attempt #2/5: java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked, sleep 1s and then retry.
java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:236)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	... 15 more
2022-10-30 19:59:58,901 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: Unable to acquire file lock on path /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock
2022-10-30 19:59:58,902 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: It appears that another process has already locked the storage directory: /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-30 19:59:58,902 [pool-22-thread-1] WARN org.apache.ratis.util.FileUtils: FAILED "tryLock /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock", attempt #3/5: java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked, sleep 1s and then retry.
java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:236)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	... 15 more
2022-10-30 19:59:59,365 [EndpointStateMachine task thread for localhost/127.0.0.1:9861 - 0 ] INFO org.apache.hadoop.ozone.container.ozoneimpl.OzoneContainer: Attempting to start container services.
2022-10-30 19:59:59,366 [EndpointStateMachine task thread for localhost/127.0.0.1:9861 - 0 ] INFO org.apache.hadoop.ozone.container.ozoneimpl.OzoneContainer: Background container scanner has been disabled.
2022-10-30 19:59:59,397 [EndpointStateMachine task thread for localhost/127.0.0.1:9861 - 0 ] INFO org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis: Starting XceiverServerRatis 7a4d425e-0004-4270-a08b-7d52bd28d47e
2022-10-30 19:59:59,903 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: Unable to acquire file lock on path /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock
2022-10-30 19:59:59,903 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: It appears that another process has already locked the storage directory: /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-30 19:59:59,904 [pool-22-thread-1] WARN org.apache.ratis.util.FileUtils: FAILED "tryLock /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock", attempt #4/5: java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked, sleep 1s and then retry.
java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:236)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	... 15 more
2022-10-30 20:00:00,904 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: Unable to acquire file lock on path /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e/in_use.lock
2022-10-30 20:00:00,904 [pool-22-thread-1] ERROR org.apache.ratis.server.storage.RaftStorageDirectory: It appears that another process has already locked the storage directory: /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e
java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-30 20:00:00,905 [EndpointStateMachine task thread for localhost/127.0.0.1:9861 - 0 ] WARN org.apache.hadoop.ozone.container.common.statemachine.EndpointStateMachine: Unable to communicate to SCM server at localhost:9861 for past 0 seconds.
java.io.IOException: Failed to lock storage /ozone/data/meta/ratis/bf265839-605b-3f16-9796-c5ba1605619e. The directory is already locked
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:236)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lambda$lock$0(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.util.JavaUtils.attempt(JavaUtils.java:166)
	at org.apache.ratis.util.FileUtils.attempt(FileUtils.java:41)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.lock(RaftStorageDirectoryImpl.java:194)
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.analyzeStorage(RaftStorageDirectoryImpl.java:153)
	at org.apache.ratis.server.storage.RaftStorageImpl.analyzeAndRecoverStorage(RaftStorageImpl.java:97)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:67)
	at org.apache.ratis.server.storage.RaftStorageImpl.<init>(RaftStorageImpl.java:52)
	at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:114)
	at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:197)
	at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$4(RaftServerProxy.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.apache.ratis.server.storage.RaftStorageDirectoryImpl.tryLock(RaftStorageDirectoryImpl.java:227)
	... 15 more
2022-10-30 20:30:59,412 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:31:03,413 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:32:55,426 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:34:33,433 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:34:55,439 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:35:15,446 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:36:49,456 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:37:15,461 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:40:51,478 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:42:51,486 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:48:45,512 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:51:45,525 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 20:59:55,981 [Periodic HDDS volume checker] INFO org.apache.hadoop.ozone.container.common.volume.ThrottledAsyncChecker: Scheduling a check for /tmp/hadoop-rhel9dev/dfs/data/hdds
2022-10-30 20:59:55,981 [Periodic HDDS volume checker] INFO org.apache.hadoop.ozone.container.common.volume.StorageVolumeChecker: Scheduled health check for volume /tmp/hadoop-rhel9dev/dfs/data/hdds
2022-10-30 20:59:56,014 [Periodic HDDS volume checker] INFO org.apache.hadoop.ozone.container.common.volume.ThrottledAsyncChecker: Scheduling a check for /ozone/data/meta/ratis
2022-10-30 20:59:56,014 [Periodic HDDS volume checker] INFO org.apache.hadoop.ozone.container.common.volume.StorageVolumeChecker: Scheduled health check for volume /ozone/data/meta/ratis
2022-10-30 21:00:27,562 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:01:27,566 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:08:11,594 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:08:37,596 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:09:55,605 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:10:45,609 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
2022-10-30 21:11:41,614 [Datanode State Machine Thread - 0] ERROR org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState: Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
	at org.apache.hadoop.ozone.container.common.statemachine.StateContext.execute(StateContext.java:629)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.start(DatanodeStateMachine.java:269)
	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.lambda$startDaemon$0(DatanodeStateMachine.java:456)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.lambda$execute$0(RunningDatanodeState.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
